"""changed enum typo in pharmacy verification column

Revision ID: 50224f55acf3
Revises: 88ad256971ce
Create Date: 2024-08-14 00:25:00.141262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50224f55acf3'
down_revision = '88ad256971ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('verification',
               existing_type=mysql.ENUM('verified', 'unverfied'),
               type_=sa.Enum('verified', 'unverified'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('verification',
               existing_type=sa.Enum('verified', 'unverified'),
               type_=mysql.ENUM('verified', 'unverfied'),
               existing_nullable=True)

    # ### end Alembic commands ###
