"""

Revision ID: 7cffaa5a905d
Revises: cb4872d1d1cb
Create Date: 2024-11-06 00:15:42.738630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cffaa5a905d'
down_revision = 'cb4872d1d1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=mysql.ENUM('ACCOUNTS', 'IT', 'HR'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=mysql.ENUM('ACCOUNTS', 'IT', 'HR'),
               nullable=False)

    # ### end Alembic commands ###
