"""adjusted enum column for verfied status in hospital

Revision ID: 88ad256971ce
Revises: 
Create Date: 2024-08-09 01:24:49.541042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88ad256971ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('verification',
               existing_type=mysql.ENUM('verified', 'unverfied'),
               type_=sa.Enum('verified', 'unverified'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('verification',
               existing_type=sa.Enum('verified', 'unverified'),
               type_=mysql.ENUM('verified', 'unverfied'),
               existing_nullable=True)

    # ### end Alembic commands ###
