"""changed users table schema

Revision ID: 92c3b59e77fe
Revises: 
Create Date: 2024-10-15 21:30:22.558276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c3b59e77fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('contact')
        batch_op.drop_index('emergency_contact')
        batch_op.drop_index('national_id')
        batch_op.drop_column('contact')
        batch_op.drop_column('national_id')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', mysql.ENUM('male', 'female', 'trans', 'other'), nullable=False))
        batch_op.add_column(sa.Column('emergency_contact', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('national_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact', mysql.VARCHAR(length=30), nullable=False))
        batch_op.create_index('national_id', ['national_id'], unique=True)
        batch_op.create_index('emergency_contact', ['emergency_contact'], unique=True)
        batch_op.create_index('contact', ['contact'], unique=True)

    # ### end Alembic commands ###
