"""changed coumn name

Revision ID: b11283b93ef3
Revises: f892ac4b7e44
Create Date: 2024-10-20 00:45:55.704168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b11283b93ef3'
down_revision = 'f892ac4b7e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_end', sa.Date(), nullable=True))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_column('planned_end_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'employee'),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'leave', 'inactive'),
               nullable=True,
               existing_server_default=sa.text("'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'leave', 'inactive'),
               nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'employee'),
               nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_end_date', sa.DATE(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('to_end')

    # ### end Alembic commands ###
