"""change org column names

Revision ID: de7d9afd628a
Revises: 9541b61356bd
Create Date: 2024-11-05 23:38:30.081976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de7d9afd628a'
down_revision = '9541b61356bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalemployees', sa.Integer(), nullable=False))
        batch_op.drop_column('employees_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employees_total', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('totalemployees')

    # ### end Alembic commands ###
