"""fixed typo in jobtitle column on users table

Revision ID: e3789e9d9ad3
Revises: 54108ed9c628
Create Date: 2024-10-27 22:13:05.824933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3789e9d9ad3'
down_revision = '54108ed9c628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('job_title',
               existing_type=mysql.ENUM('hr', 'developer', 'accoutant'),
               type_=sa.Enum('hr', 'developer', 'accountant'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('job_title',
               existing_type=sa.Enum('hr', 'developer', 'accountant'),
               type_=mysql.ENUM('hr', 'developer', 'accoutant'),
               existing_nullable=False)

    # ### end Alembic commands ###
