"""changed users table schema

Revision ID: e7743404509b
Revises: 92c3b59e77fe
Create Date: 2024-10-15 21:45:23.459643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7743404509b'
down_revision = '92c3b59e77fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['national_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('national_id')

    # ### end Alembic commands ###
